<?php // $Id$

/**
 * @file
 * Drupal Status module main file
 *
 * It is responsible for handling most of the request which
 * are not administrative tasks.
 */

define('DRUPAD_CURRENT_VERSION', '1.2');

/**
 * Implementation of hook_menu
 */
function drupad_menu() {
  $items = array();

  // Module settings
  $items['admin/config/drupad'] = array(
    'title' => 'Drupad',
    'description' => 'Configure Drupad',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupad_settings_form'),
    'access arguments' => array('administer Drupad'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'drupad.admin.inc',
  );

  // Special callback to check config
  $items['drupad/check-config/%'] = array(
    'page callback' => 'drupad_check_config',
    'page arguments' => array(2),
    'access callback' => 'drupad_authorize',
    'type' => MENU_CALLBACK,
  );

  // Items for the client application, those are based
  // on module capacity to serve those services (modules presence)
  // and also settings defined by the administrator
  $items += drupad_generate_menu_callbacks();

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function drupad_permission() {
  return array(
    'administer Drupad' => array(
      'title' => t('Administer Drupad'),
      'description' => t('Configure features enabled for Drupad application.'),
    ),
    'use Drupad application' => array(
      'title' => t('Use Drupad application'),
      'description' => t('Access the website from Drupad application.'),
    ),
  );
}

/**
 * Check wether the current user has privilege for this callback
 *
 * Access callback fired on every client application request which
 * will determine if the current logged in user (via the application)
 * can or cannot access the current callback
 *
 * @return boolean
 */
function drupad_authorize() {
  global $user;
  if (!strstr($_SERVER['HTTP_USER_AGENT'], 'Drupad')) {
     return FALSE;
  }
  if ($user->uid == 0) {
    return FALSE;
  }
  if (user_access('use Drupad application')) {
    return TRUE;
  }
  if ($user->uid == 1) {
    return TRUE;
  }
  // if (arg(0) == 'drupad') {
  //     drupad_unauthorized();
  //   }
  return FALSE;
}

/**
 * Implementation of hook_init() for HTTP Basic auth
 *
 * This hook_init() implementation is responsible for challenging
 * the client with an HTTP Basic authentification based on the current
 * Drupal installation, i.e. login + password. This allows us to log in
 * the user seemlessly from the client application.
 *
 * If credentials given by the client are not correct, the challenge
 * returns a unauthorized response.
 *
 * @see drupad_unauthorized()
 */
function drupad_init() {
  if (arg(0) == 'drupad' /* && strstr($_SERVER['HTTP_USER_AGENT'], 'Drupad') */ ) {
    // Load credentials.
    if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {
      $name = $_SERVER['PHP_AUTH_USER'];
      $pass = $_SERVER['PHP_AUTH_PW'];
    }
    elseif (isset($_GET['HTTP_AUTHORIZATION'])) {
      list($name, $pass) = drupad_parse_header($_GET['HTTP_AUTHORIZATION']);
    }
    elseif (!isset($_GET['HTTP_AUTHORIZATION']) && isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
      list($name, $pass) = drupad_parse_header($_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
    }
    elseif (!isset($_GET['HTTP_AUTHORIZATION']) && !isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']) && isset($_GET['login'])) {
      list($name, $pass) = drupad_parse_header($_GET['login']);
    }

    global $user;
    require_once('includes/form.inc');
    drupal_load('module', 'user');

    if (isset($name) && isset($pass)) {
      // Abort if the user with the provided credentials is already logged in.
      if ($user->uid != 0 && strcasecmp($user->name, $name) == 0) {
        return;
      }
      elseif (!user_is_anonymous()) {
        drupad_user_logout();
        exit();
      }

      if (user_is_blocked($name) || drupal_is_denied('user', $name)) {
        drupad_unauthorized();
        exit();
      }
      if ($uid = user_authenticate($name, $pass)) {
        $user = user_load($uid);
        $edit = array();
        user_login_finalize($edit);
      }
      else {
        drupad_unauthorized();
        exit();
      }
    }
    else {
      drupad_unauthorized();
      exit();
    }
  }
}

/**
 * Set 401 Unauthorized status and WWW-Authenticate header.
 */
function drupad_unauthorized() {
  require_once('includes/common.inc');
  require_once('includes/unicode.inc');

  $site_name = trim(variable_get('site_name', 'drupal'));
  $realm = mime_header_encode($site_name);

  drupal_add_http_header("HTTP/1.0", "401 Unauthorized");
  drupal_add_http_header("WWW-Authenticate", "Basic realm=\"$realm\"");

  // User is logged in, so delete her session
  if (!user_is_anonymous()) {
    global $user;
    watchdog('user', 'Session closed for %name.', array('%name' => $user->name));
    // Destroy the current session:
    session_destroy();
    // Only variables can be passed by reference workaround.
    $null = NULL;
    user_module_invoke('logout', $null, $user);
    // Load the anonymous user
    $user = drupal_anonymous_user();
  }
  print $site_name;
}

/**
 * Parse an HTTP authorization header.
 */
function drupad_parse_header($header) {
  list($type, $credentials) = split(' ', $header);
  if ($type == 'Basic') {
    return explode(':', base64_decode($credentials));
  }
}

/**
 * Module response server
 *
 * The module response server is responsible for taking an array
 * containing information that should be sent back to the client
 * application.
 *
 * The response server is also responsible for determining if
 * a proper JSON encoder is available, and if not includes the
 * required libraries to actually send a proper formatted JSON
 * reponse.
 *
 * The server also sets the HTTP response header to 'text/javascript'
 * as all data are sent back in a JSON formatted string.
 *
 * Finally the server stops the current process with a die() call
 * because the request is terminated.
 *
 * @param $data
 *   An associative array containing every element needed by the client
 *   application.
 */
function drupad_serve_response($data) {
  $messages = drupal_get_messages(NULL, TRUE);
  drupal_json_output($data);
  die();
}

/**
 * @param $application_version
 *   The client application version number extracted
 *   from the HTTP request arg(2)
 *
 * @return
 *   An associative array containing the current module version
 *   and available services that the application can implement
 *   with callback to access those features.
 *
 * @see drupad_serve_response()
 */
function drupad_check_config($application_version = NULL) {
  if (!$application_version) {
    drupal_not_found();
  }

  $data = $callbacks = $modules = $permissions = array();

  // The current version of the module
  $data['meta']['version'] = DRUPAD_CURRENT_VERSION;
  $data['content'] = array();

  if (($data['meta']['version_match'] = drupad_version_match(DRUPAD_CURRENT_VERSION, $application_version)) === TRUE) {

    $available_callbacks = drupad_available_callbacks($only_available = TRUE);

    foreach ($available_callbacks as $callback => $item) {
      // Only if this callback is enabled
      if ( (bool) variable_get('drupad_callback_' . $callback, 1) === TRUE) {
        $callbacks[] = $callback;
        foreach ($item['modules'] as $module) {
          $modules[] = $module;
        }

        // Check for optional modules
        if (isset($item['modules_optional']) && is_array($item['modules_optional']) && count($item['modules_optional']) > 0) {
          foreach ($item['modules_optional'] as $module) {
            if (module_exists($module)) {
              $modules[] = $module;
            }
          }
        }

        // Check for needed permissions
        if (is_array($item['permissions']) && count($item['permissions']) > 0) {
          foreach ($item['permissions'] as $perm) {
            if (user_access($perm)) {
              $permissions[] = $perm;
            }
          }
        }

      }
    }
    $data['content']['callbacks'] = $callbacks;
    $data['content']['modules'] = array_values(array_unique($modules));
    $data['content']['permissions'] = array_values(array_unique($permissions));
  }

  drupad_serve_response($data);
}

/**
 * Determine if the client application and the module are compatible
 *
 * Base on the 2 version numbers, the function will determine if
 * the client application is compatible with the current version
 * of the module.
 *
 * @param $module_version
 *
 * @param $application_version
 *
 * @return BOOLEAN
 */
function drupad_version_match($module_version, $application_version) {
  // Lists application version compatible with this version
  // of the module.
  $application_versions_for_module = array('1.2');

  return in_array($application_version, $application_versions_for_module);
}

/**
 * @return Available services implemented by
 *  by the module (most of the time, module name)
 */
function drupad_available_callbacks($only_available = FALSE) {
  $callbacks = array();

  $callbacks['comments'] = array(
    'title' => t('Comments'),
    'description' => t('View, post and moderate comments. You must have the <strong>Comment</strong> module enabled. Used permissions: <strong>access comments</strong>, <strong>administer comments</strong>, <strong>post comments</strong>, <strong>post comments without approval</strong>.'),
    'modules' => array('comment'),
    'modules_optional' => array('mollom'),
    'permissions' => array('access comments', 'administer comments', 'post comments', 'post comments without approval'),
    'section' => 'Content',
    'has_pager' => TRUE,
  );

  $callbacks['content'] = array(
    'title' => t('Content'),
    'description' => t('View content, moderate, delete content and change content sticky and promoted state. Used permissions: <strong>access content</strong>, <strong>administer nodes</strong>.'),
    'modules' => array('node'),
    'modules_optional' => array('mollom'),
    'permissions' => array('access content', 'administer nodes'),
    'section' => 'Content',
    'has_pager' => TRUE,
  );

  $callbacks['users'] = array(
    'title' => t('Users'),
    'description' => t('Active, block and delete users. Used permission: <strong>administer users</strong>.'),
    'modules' => array('user'),
    'permissions' => array('administer users'),
    'section' => 'Content',
    'has_pager' => TRUE,
  );

  $callbacks['updates'] = array(
    'title' => t('Available updates'),
    'description' => t('List projects status and display available updates plus security warnings. You must have the <strong>Update status</strong> module enabled. Used permission: <strong>administer site configuration</strong>.'),
    'modules' => array('update'),
    'permissions' => array('administer site configuration'),
    'section' => 'System',
  );

  $callbacks['status-report'] = array(
    'title' => t('Status report'),
    'description' => t('Gives an overview of your Drupal installation health. Used permission: <strong>administer site configuration</strong>.'),
    'modules' => array('system'),
    'permissions' => array('administer site configuration'),
    'section' => 'System',
  );

  $callbacks['offline'] = array(
    'title' => t('Maintenance mode'),
    'description' => t('Allows your to turn your site offline. Used permission: <strong>administer site configuration</strong>.'),
    'modules' => array('system'),
    'permissions' => array('administer site configuration'),
    'section' => 'System',
  );

  $callbacks['cron-tasks'] = array(
    'title' => t('Cron'),
    'description' => t('Launch cron tasks. Used permission: <strong>administer site configuration</strong>.'),
    'modules' => array('system'),
    'permissions' => array('administer site configuration'),
    'section' => 'System',
  );

  $callbacks['dblog'] = array(
    'title' => t('Recent log entries'),
    'description' => t('View recent log entries. You must have the <strong>Database logging</strong> module enabled. Used permission: <strong>access site reports</strong>.'),
    'modules' => array('dblog'),
    'permissions' => array('access site reports'),
    'section' => 'System',
  );

  $callbacks['backup'] = array(
    'title' => t('Backup'),
    'description' => t('Perform a database backup of your site. You must have the <strong>Backup and Migrate</strong> module installed and enabled. Used permission: <strong>perform backup</strong>.'),
    'modules' => array('backup_migrate'),
    'permissions' => array('perform backup'),
    'section' => 'System',
  );

  foreach ($callbacks as $callback => $service) {
    foreach ($service['modules'] as $module) {
      if (!module_exists($module)) {
        if ($only_available) {
          unset($callbacks[$callback]);
          continue;
        }
        else {
          $callbacks[$callback]['disabled'] = TRUE;
          continue;
        }
      }
    }
  }

  return $callbacks;
}

/**
 * Formats every callback into a suitable Drupal menu item
 *
 * @return associative array of menu items
 */
function drupad_generate_menu_callbacks() {
  $items = array();

  foreach (drupad_available_callbacks($only_available = TRUE) as $callback => $item) {
    if ( (bool) variable_get('drupad_callback_' . $callback, 1) === TRUE) {
      $page_callback = str_replace('/%', '', $callback);
      $page_callback = str_replace(array('/', '-'), '_', $page_callback);

      $items['drupad/' . $callback] = $item;
      $items['drupad/' . $callback]['page callback'] = 'drupad_' . $page_callback;
      $items['drupad/' . $callback]['access callback'] = 'drupad_authorize';
      $items['drupad/' . $callback]['file'] = 'includes/' . $page_callback . '.inc';
      $items['drupad/' . $callback]['type'] = MENU_CALLBACK;
    }
  }

  return $items;
}

/**
 * This function does exactly what core function
 * user_logout() does expect that there is no final
 * redirection with drupal_goto()
 *
 * @see http://api.drupal.org/api/function/user_logout/6
 */
function drupad_user_logout() {
  global $user;

  watchdog('user', 'Session closed for %name.', array('%name' => $user->name));

  // Destroy the current session:
  session_destroy();
  // Only variables can be passed by reference workaround.
  $null = NULL;
  user_module_invoke('logout', $null, $user);

  // Load the anonymous user
  $user = drupal_anonymous_user();
}